language: go

go:
  - 1.13.x

sudo: required

env:
  - GO111MODULE=on

install: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev libnetfilter-queue-dev iptables-dev
  - go get github.com/mattn/goveralls

script:
  - go build
  - go test
